language: python
matrix:
  include:
  - name: "Ubuntu 16.04 (Xenial) with Python 3.5"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    python: 3.5
  - name: "Fedora Core 29 (Docker) with Python 3.7"
    env: FEDORA_VERSION="29"
    os: linux
    dist: bionic
    sudo: required
    group: edge
    language: python
    python: 3.7
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 3.6"
    env: UBUNTU_VERSION="18.04"
    os: linux
    dist: bionic
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "MacOS 10.14 with Python 3.7"
    os: osx
    osx_image: xcode10
    language: generic
install:
- ./travis/install.sh
script:
- ./travis/run_tests.sh
