language: python
matrix:
  include:
  - name: "Ubuntu 16.04 (Xenial) with Python 2.7"
    env: TARGET="linux"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    python: 2.7
  - name: "Ubuntu 16.04 (Xenial) with Python 3.5"
    env: TARGET="linux"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    python: 3.5
  - name: "Mac OS with Python 2.7"
    env: TARGET="macos"
    os: osx
    osx_image: xcode8.3
    language: generic
    env: PYTHONPATH=/Library/Python/2.7/site-packages/
  - name: "Centos 7 (Docker) with Python 2.7"
    env: CENTOS_VERSION="7"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    services:
    - docker
  - name: "Fedora Core 29 (Docker) with Python 2.7"
    env: FEDORA_VERSION="29"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    services:
    - docker
  - name: "Fedora Core 29 (Docker) with Python 3.7"
    env: FEDORA_VERSION="29"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.7
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 2.7"
    env: UBUNTU_VERSION="18.04"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 3.6"
    env: UBUNTU_VERSION="18.04"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
install:
- ./travis/install.sh
script:
- ./travis/run_tests.sh
