#!/bin/bash
#
# Script to run Python 2 tests on Travis-CI.
#
# This file is generated by l2tdevtools update-dependencies.py, any dependency
# related changes should be made in dependencies.ini.

# Exit on error.
set -e;

python2 setup.py update

python2 setup.py build

PYTHONPATH=`ls -1d build/lib.*` python2 run_tests.py

python2 setup.py sdist

python2 setup.py bdist
