#!/bin/bash
#
# Script to run Python tests on Travis-CI.
#
# This file is generated by l2tdevtools update-dependencies.py, any dependency
# related changes should be made in dependencies.ini.

# Exit on error.
set -e;

python setup.py update

python setup.py build

PYTHONPATH=`ls -1d build/lib.*` python run_tests.py

python setup.py sdist

python setup.py bdist
